### ISSUE TITLE
How to train data?

### ISSUE THREAD

**Issue by dhana-exe** [WanderingEye0/The-Gatherer#2]
Hello, ummm any steps to train the data?
i can't figured out how to do it

can you share it?
i think i will train the data and push merge to this github if you allow me :)

**Comment by Riczap** [comment]
Hi! I'm going to try and upload a detailed guide on how to train a custom model, but in the meantime you can just take screenshots of the game like in the google drive folder I uploaded and follow this tutorial https://www.youtube.com/watch?v=GRtgLlwxpc4
