### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by Gajuz** [WanderingEye0/The-Gatherer#4]
Hey, when I try to install I get error: ModuleNotFoundError: No module named 'win32gui'
I dont know whether this is my problem on problem on your side, if its a problem on my side can you help me with installation please? My instagram is @sometechdudejak

**Comment by Riczap** [comment]
Hi! you just need to activate your environment and use `pip install win32gui`, I forgot to add the dependencies for the window capture to the requirements.txt file.
Sorry!

**Comment by Gajuz** [comment]
> Hi! you just need to activate your environment and use `pip install win32gui`, I forgot to add the dependencies for the window capture to the requirements.txt file.
> Sorry!

Thanks so much man!:)

**Comment by Riczap** [comment]
Done! I updated the requirements.txt file to add pywin32.
And no problem.
