### ISSUE TITLE
download issue

### ISSUE THREAD

**Issue by idontknowwhatamdoin** [WanderingEye0/The-Gatherer#5]
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:270: error: (-5:Bad argument) Can't read ONNX file: models/custom_yolov5.onnx in function 'cv::dnn::dnn4_v20221220::ONNXImporter::ONNXImporter'

I got this error can you help me?

**Comment by Riczap** [comment]
I think that can be solved by uninstalling and reinstalling opencv in the lastest version.

**Comment by Gajuz** [comment]
and how do i do that? xd My name on github is pretty accurate lmao

**Comment by Riczap** [comment]
> and how do i do that? xd My name on github is pretty accurate lmao

Okay okay, are you using conda or just straight on python?

**Comment by Gajuz** [comment]
im using conda

**Comment by Riczap** [comment]
> im using conda

So, you just need to activate your environment and type `pip uninstall opencv-python` and then try using `pip install opencv-python` and run the program again. 
I think that might work.

**Comment by Gajuz** [comment]
again

 cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:270: error: (-5:Bad argument) Can't read ONNX file: models/custom_yolov5.onnx in function 'cv::dnn::dnn4_v20221220::ONNXImporter::ONNXImporter'

**Comment by Riczap** [comment]
Let me check something, give me a moment. It might be the way that the model was exported, I'm uploading a new one to test it.

**Comment by Riczap** [comment]
Could you try to replace the custom_yolov5.onnx model with this one? I think that could be the problem too.
https://drive.google.com/file/d/1UJicc6twkfJKq1r4Mx4m6uhyR2MPE1DE/view?usp=share_link

**Comment by Riczap** [comment]
Try replacing the custom_yolov5.onnx file with this one: https://drive.google.com/file/d/1utFqokKwKdqD2IXbYJRGaIp0eFu53wB6/view?usp=share_link

**Comment by Gajuz** [comment]
Yes man, it works for me now, I replaced those two onnx files with the custom one you gave me and it works

**Comment by Riczap** [comment]
Okay, I'm going to update the main files with the new ones then, thanks!
Edit: I forgot to update the name of the default model on the main file! that's why it wasn't actually working, my bad.

**Comment by nekzzx1** [comment]
Traceback (most recent call last):
  File "C:\Users\ez\Desktop\The-Gatherer-The-Gatherer-2.0\main.py", line 1, in <module>
    import customtkinter as ctk
ModuleNotFoundError: No module named 'customtkinter'

**Comment by Riczap** [comment]
> Traceback (most recent call last):
>   File "C:\Users\ez\Desktop\The-Gatherer-The-Gatherer-2.0\main.py", line 1, in <module>
>     import customtkinter as ctk
> ModuleNotFoundError: No module named 'customtkinter'

It looks like you didn't installed the requirements properly, you're missing the customtkinter package, just run `pip install customtkinter`
