### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by idontknowwhatamdoin** [WanderingEye0/The-Gatherer#6]
FileNotFoundError: [Errno 2] No such file or directory: 'models/custom_yolov5.txt'

**Comment by Riczap** [comment]
You just have to rename that file in the models folder to "rough_stone.txt" I have to rename it on the repo.

**Comment by Riczap** [comment]
I changed the name of the model, I have to update some of the default names inside of the main code, I'll do it later today, sorry!

**Comment by Riczap** [comment]
Hi! I updated the main file, it should work now, just download the new version and it should be working fine.
