### ISSUE TITLE
Same Object Issue

### ISSUE THREAD

**Issue by niicholai** [WanderingEye0/The-Gatherer#8]
Installed for Python, got all the dependencies, etc.

Ran it, set my Albion to 1920x1080 windowed (I have a 1440p monitor), told it to go after checking vision.

All it does is keep clicking the same rock even if it's depleted. If I run around a bit it will click another rock then just keep clicking the same rock repeatedly.

What can I do?

**Comment by Riczap** [comment]
I think that's probably a problem with the model due to lack of training data. I trained a model on about 100 images just to test the bot, so sadly, the way to fix the issue would be to retrain it with more data.
